version: '3.8'
services:
  fablab-font:
    build:
      context: .
      args:
        - REACT_APP_API_URL=http://172.16.9.13:5000
    ports:
      - 3000:3000
      - 80:80
volumes:
  db:
networks:
  backend:
  frontend:
